name = "moldes"
version = "0.1.0"
license = "license"
author = "jscilipoti"
maintainer = "jscilipoti@gmail.com"
copyright = "Copyright 2023, jscilipoti"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
